services:
  - type: web
    name: bezaleelcourt-1
    env: python
    region: oregon  # Change if needed
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn property.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        sync: false  # Add manually in Render dashboard
      - key: SUPABASE_URL
        value: https://kwoimnikoqaiaollnuny.supabase.co
      - key: SUPABASE_KEY
        sync: false  # Add manually in Render dashboard
