# Generated by Django 4.2.18 on 2025-02-06 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(default=home.models.generate_property_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, choices=[('commercial_land', 'Commercial Land'), ('office_space', 'Office Space'), ('residential_land', 'Residential Land'), ('apartments', 'Apartments'), ('bungalows', 'Bungalows'), ('fully_detached_duplexes', 'Fully Detached Duplexes'), ('semi_detached_duplexes', 'Semi Detached Duplexes'), ('terrace_duplexes', 'Terrace Duplexes'), ('maisonettes', 'Maisonettes'), ('penthouses', 'Penthouses')], max_length=50, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.property')),
            ],
        ),
    ]
