# Generated by Django 4.2.18 on 2025-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
