# Generated by Django 4.2.18 on 2025-02-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Property_type',
            field=models.CharField(blank=True, choices=[('Villa', 'Villa'), ('Studio', 'Sudio'), ('Office', 'Office')], default='Villa', max_length=50, null=True),
        ),
    ]
