# Generated by Django 4.2.18 on 2025-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('off_plan_houses', 'Off Plan Houses'), ('apartments', 'Apartments'), ('duplexes', 'Duplexes'), ('bungalows', 'Bungalows'), ('fully_detached_duplexes', 'Fully Detached Duplexes'), ('semi_detached_duplexes', 'Semi Detached Duplexes'), ('terrace_duplexes', 'Terrace Duplexes'), ('maisonettes', 'Maisonettes'), ('penthouses', 'Penthouses'), ('lands', 'Lands')], default='apartments', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(blank=True, choices=[('off_plan_houses', 'Off Plan Houses'), ('apartments', 'Apartments'), ('duplexes', 'Duplexes'), ('bungalows', 'Bungalows'), ('fully_detached_duplexes', 'Fully Detached Duplexes'), ('semi_detached_duplexes', 'Semi Detached Duplexes'), ('terrace_duplexes', 'Terrace Duplexes'), ('maisonettes', 'Maisonettes'), ('penthouses', 'Penthouses'), ('lands', 'Lands')], max_length=50, null=True),
        ),
    ]
