# Generated by Django 4.2.18 on 2025-01-30 09:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_property_address_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(default=home.models.generate_property_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(blank=True, choices=[('land_to_sell', 'Land to Sell'), ('building_to_sell', 'Building to Sell')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
