# Generated by Django 4.2.18 on 2025-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_property_property_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(blank=True, choices=[('land_to_sell', 'land_to_sell'), ('building_to_sell', 'building_to_sell')], max_length=50, null=True),
        ),
    ]
