# Generated by Django 4.2.18 on 2025-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_property_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
